### ISSUE TITLE
Implement home page into redux

### ISSUE THREAD

**Issue by dilipMaharjan** [WycliffeAssociates/translationExchange#247]
## User Story
As a developer, I want to refactor home page so that it can use the redux 

## Acceptance Criteria
- [x] Displays the home page with out issues.

## Tasks
- [x] Convert the design to adjust to redux
- [x] Fetch needed data
- [x] Make sure navigation to other page is not broken
