### ISSUE TITLE
Implement projects page in redux

### ISSUE THREAD

**Issue by dilipMaharjan** [WycliffeAssociates/translationExchange#248]
## User Story
As a facilitator/checker I would like all the projects that are available to me as a result of my filter choices (later to include log-in privileges) to be displayed on the page for me to chose from so that I may continue work on an existing project.

## Acceptance Criteria
- [x] Displays the projects without issues.
- [x] Data for choosing projects are fetched properly

## Tasks
- [ ] Convert the design to adjust to redux
- [x] Fetch needed data
- [x] Make sure navigation to other page is not broken

**Comment by dilipMaharjan** [comment]
Conversion to redux at the moment is not necessary but can be converted easily.
