### ISSUE TITLE
Implement (Download,Mark published) page in redux 

### ISSUE THREAD

**Issue by dilipMaharjan** [WycliffeAssociates/translationExchange#250]
## User Story
As a developer, I want to refactor  (Download,Mark published) so that it can use the redux 

## Acceptance Criteria
- [x] Displays the (Download,Mark published) page with out issues.
- [x] Displays the correct data according to project chosen such as checking level,contributors,translations types

## Tasks
- [x] Convert the design to adjust to redux
- [x] Fetch needed data
- [x] Make sure fetch data is in accordance to chosen project 
- [x] Make sure navigation to other page is not broken
