### ISSUE TITLE
Implement chunk list page in redux

### ISSUE THREAD

**Issue by dilipMaharjan** [WycliffeAssociates/translationExchange#252]
## User Story
As a facilitator/checker I would like to have all of the available takes for the chapter displayed on the screen so that I may interact with the card/wavs to evaluate and make decisions regarding individual takes in the checking/publishing process.

Refactored in to Redux using TDD

## Acceptance Criteria
- [ ] Design is converted to redux without issues
- [ ] List of Chunk is fetched

## Tasks
- [ ] Convert present design to adopt redux
- [ ] Convert fetch list of chunks and display
