### ISSUE TITLE
Implement project title and comment in chunk list page

### ISSUE THREAD

**Issue by dilipMaharjan** [WycliffeAssociates/translationExchange#253]
## User Story
As a developer, I want to refactor project title and comment in chunk list page so that it can use the redux 

## Acceptance Criteria
- [x] Displays the project title without issues.
- [x] Displays comment icon
- [x] Able to comment on chapter

## Tasks
- [x] Convert the design to adjust to redux
- [x] Audio save, edit, delete after recording comment
