### ISSUE TITLE
Implement list source audio projects in chunk list page

### ISSUE THREAD

**Issue by dilipMaharjan** [WycliffeAssociates/translationExchange#254]
## User Story
As a developer, I want to refactor list source audio in  chunk list page so that it can use redux.

## Acceptance Criteria
- [x] Design is converted to redux with out issues
- [x] list of available source audio is fetched

## Tasks
- [x] Convert present design to adopt redux
- [x] Convert fetch list of source audio and display
