### ISSUE TITLE
Notify to the user that a comment was successfully  saved 

### ISSUE THREAD

**Issue by antonlopez** [WycliffeAssociates/translationExchange#287]
## User Story
As a facilitator/checker, I would like translationExchange to notify me when a comment was successfully saved. 

## Acceptance criteria
- [ ] A notification must be displayed indicating that a comment was saved. 

## Tasks
- [ ] Find a npm package  that displays user friendly notifications. 
- [ ] Display notifications when a comments is saved.
