### ISSUE TITLE
Translation Exchange auto start on raspberry pi 

### ISSUE THREAD

**Issue by antonlopez** [WycliffeAssociates/translationExchange#290]
## User Story
As a facilitator/checker, I would like Translation Exchange to start as soon as I turn on the raspberry pi by doing this I do not have to open the terminal and execute the commands to start it.
 
## Acceptance criteria
- [ ] Translation Exchange needs to start automatically  once the raspberry pi is turn on.

## Tasks
- [ ] Research about shell scripts. 
- [ ] Research about how to execute shell scripts at startup. 
- [ ] Create shell scripts and execute them at startup.
- [ ] Test the time of deployment.
