### ISSUE TITLE
Ability to record audio comments

### ISSUE THREAD

**Issue by erica-zhong** [WycliffeAssociates/translationExchange#33]
## User Story
As a translator, I want to be able to record multiple audio comments on a take to give feedback

## Acceptance Criteria
- [x] UI to record an audio comment

## Tasks
- [x] UI for recording an audio comment
- [ ] way to store recorded comments
