### ISSUE TITLE
User ID Interface

### ISSUE THREAD

**Issue by nathanalbers** [WycliffeAssociates/translationExchange#39]
## User Story
As a translator, I want a way to identify myself so the system can track my contributions

## Acceptance Criteria
- [ ] There is a UI to enter a name (or image) for me to be identified by

## Tasks
- [ ] UI for identifying myself to the system
- [ ] The app stores the person's identity so it remembers it when you navigate to another page (cookie?)

## Questions
1. How is the best way for users who are illiterate to identify themselves (pictures?)
