### ISSUE TITLE
Create 'Guest' Account

### ISSUE THREAD

**Issue by nathanalbers** [WycliffeAssociates/translationExchange#41]
## User Story
As a consumer of Scripture, I want to be able to listen to translations (including stitched together ones) even when I'm not a contributor

## Acceptance Criteria
- [ ] I can listen to translations without identifying myself 
- [ ] I can 'log out' or choose not to identify myself

## Tasks
- [ ] Only pop up UI for logging in when the user tries to do something that requires identification
- [ ] When you're logged in, button for "log out"/clear identity

**Comment by Redmayspecial** [comment]
@nathanalbers   Can you add a "so that" on your user story?... something like so that I can be blessed and encourage others
