### ISSUE TITLE
Remember User Accounts (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/translationExchange#73]
## User Story
As a translator, I want my name to be remembered and available as an option to choose when I identify myself so I don't have to keep retyping my identity. 

## Acceptance Criteria
- [ ] After adding your identity, it comes up as an option next time you need to identify yourself

## Tasks
- [ ] After a user enters a new identity, send a request to the backend to store it in the database
- [ ] When the user is logging in, request the database for previously entered names

**Comment by Redmayspecial** [comment]
Closed due to design changes
