### ISSUE TITLE
Upload temporary source audio

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/translationExchange#77]
## User Story
As a translator, I want to temporarily use source audio from a .tr file for a chapter, so that I can use it for checking if I don't have any source audio associated with the chapter for the time being.

## Acceptance Criteria
- [ ] If there's no source audio for some of the takes in a chapter, you can choose a source .tr from your computer
- [ ] The audio from that .tr will be used as source audio for any takes that currently don't have source audio set
- [ ] If you navigate to another page, the .tr you chose isn't saved, and you have to choose it again if you go back to the same chapter

## Tasks
- [ ] Display button for uploading .tr only if there is some source audio missing
- [ ] Determine what takes are missing source audio
- [ ] Extract audio files from .tr as needed for those takes

**Comment by sheesania** [comment]
Where does source audio actually need to come from? Will it just be put in the backend along with projects? Does the user need to be able to upload it from the frontend app? Pick source audio to use from a list in the frontend app?

**Comment by Redmayspecial** [comment]
Closed due to design changes
