### ISSUE TITLE
Attribute Comments/Ratings with my name (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/translationExchange#78]
## User Story
As a translator, I want edits/comment/ratings I make to be attributed in the database to my name so that I can track who changed/added what.

## Acceptance Criteria
- [ ] Whenever a comment is displayed, the correct name of its author from the database is also shown

## Tasks
- [ ] When the user makes a comment, include information about their identity in the info sent to the backend database
- [ ] When displaying a comment, request information about author from the backend database

**Comment by Redmayspecial** [comment]
Closed due to design changes
